let () = Binary_search_tree_test.run_test ()
let () = Bob_test.run_test ()
let () = Bases_test.run_test ()
let () = Beers_test.run_test ()
let () = Binary_search_test.run_test ()
let () = Luhn_test.run_test ()
let () = Matching_brackets_test.run_test ()
let () = Phone_number_test.run_test ()
let () = Word_count_test.run_test ()

(* let () = Prime_factors_test.run_test () *)
let () = Roman_numerals_test.run_test ()
let () = Say_test.run_test ()
